Rails/Projekte/flix/config/routes.rb
Rails.application.routes.draw do
  
  
  root "movies#index"
  
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'

  resource :session
  resources :users

  resources :movies do
    resources :reviews
    resources :favorites
   

  end
end

Rails/Projekte/flix/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

Rails/Projekte/flix/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
    	<li><%= link_to "Alle Movies", movies_path %></li>
    </ul>
     <ul class="right">
      <% if current_user %>
        <li><%= link_to current_user.name, user_path(current_user.id) %></li>
        <li><%= link_to "SignOut", session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "SignIn", signin_path %></li> |
        <li><%= link_to "SignUp", signup_path %></li>
      <% end %>    
    </ul>
   </div>
</nav>

Rails/Projekte/flix/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

Rails/Projekte/flix/app/views/layouts/_sidebar.html.erb
<h4>Movies</h4>
<ul class="side-nav">
	<% @sidebar_movies.each do |movie| %>
	<li>				
		<%= link_to movie.title, movie_path(movie.id) %>
	</li>
	<% end %>		
</ul>

Rails/Projekte/flix/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Flix" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Flix" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row"> 
      <%= render 'layouts/navigation' %>
      <div class="row">
        <div class="large-3 columns"><%= render 'layouts/sidebar' %></div>
        <div class="large-9 columns"><%= render 'layouts/messages' %>
        <%= yield %></div>
      </div>
    </div>
  </body>
</html>