Rails/Projekte/ontrack_privat/config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  resources :projects do
    resources :validations
  end

end

Rails/Projekte/ontrack_privat/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :validations

	def get_average_ranking
		validations.average(:ranking)
	end	
end

Rails/Projekte/ontrack_privat/app/models/validation.rb
class Validation < ActiveRecord::Base
  	belongs_to :project

  	validates :comment, length: { minimum: 15, message: "Die Beschreibung muss mindestens 15 Zeichen enthalten!" }
	validates :username, :ranking, presence: { message: "Bitte alle Felder ausfüllen!" }

	RANKING_ITEMS = { "Sehr schlecht" => "1", "Schlecht" => "2", "Okay" => "3", "Gut" => "4", "Sehr gut" => "5"}
end

Rails/Projekte/ontrack_privat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/Projekte/ontrack_privat/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :start_date)
    end
end

Rails/Projekte/ontrack_privat/app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
  before_action :set_validation, only: [:show, :edit, :update, :destroy]
   before_action :set_project

  # GET /validations
  # GET /validations.json
  def index
    @validations = @project.validations
    if @validations.empty?
      redirect_to new_project_validation_path(@project)
    end
  end

  # GET /validations/1
  # GET /validations/1.json
  def show
  end

  # GET /validations/new
  def new
    @validation = Validation.new
  end

  # GET /validations/1/edit
  def edit
  end

  # POST /validations
  # POST /validations.json
  def create
    @validation = @project.validations.new(validation_params)
    

    respond_to do |format|
      if @validation.save
        format.html { redirect_to project_validations_url(@project), notice: 'Validation was successfully created.' }
        format.json { render :show, status: :created, location: @validation }
      else
        format.html { render :new }
        format.json { render json: @validation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /validations/1
  # PATCH/PUT /validations/1.json
  def update
    respond_to do |format|
      if @validation.update(validation_params)
        format.html { redirect_to project_validations_url(@project), notice: 'Validation was successfully updated.' }
        format.json { render :show, status: :ok, location: @validation }
      else
        format.html { render :edit }
        format.json { render json: @validation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /validations/1
  # DELETE /validations/1.json
  def destroy
    @validation.destroy
    respond_to do |format|
      format.html { redirect_to project_validations_url(@project), notice: 'Validation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_validation
      @validation = Validation.find(params[:id])
    end

     def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def validation_params
      params.require(:validation).permit(:comment, :username, :ranking, :project_id)
    end


end

Rails/Projekte/ontrack_privat/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/Projekte/ontrack_privat/app/helpers/projects_helper.rb
module ProjectsHelper
end

Rails/Projekte/ontrack_privat/app/helpers/validations_helper.rb
module ValidationsHelper
	def create_text(validation)
		Validation::RANKING_ITEMS.key(validation.ranking.to_s)
	end

	def show_stars(validation)
		str = ""						
		for i in 1..5
			if i <= validation.ranking then
				str += image_tag "small_full_star.gif", size: "20x20"
			else
				str += image_tag "small_empty_star.gif", size: "20x20"
			end
		end
		str.html_safe
	end

	def create_ranking(project)
		str = ""
		for i in 1..5
			if (i-0.25) <= project.get_average_ranking then
				str += image_tag "small_full_star.gif", size: "20x20"
			elsif ((i-0.75) < project.get_average_ranking && project.get_average_ranking < (i-0.25))
				str += image_tag "small_half_star.gif", size: "20x20"
			else
				str += image_tag "small_empty_star.gif", size: "20x20"
			end
		end
		str.html_safe	
	end
end

Rails/Projekte/ontrack_privat/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/ontrack_privat/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

Rails/Projekte/ontrack_privat/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.start_date %></td>
        
        <td><%= link_to 'Validations', project_validations_path(project) %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

Rails/Projekte/ontrack_privat/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

Rails/Projekte/ontrack_privat/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>
<%= link_to 'Validations', project_validations_path(@project) %> |
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

Rails/Projekte/ontrack_privat/app/views/validations/_form.html.erb
<%= form_for([@project, @validation]) do |f| %>
  <% if @validation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@validation.errors.count, "error") %> prohibited this validation from being saved:</h2>

      <ul>
      <% @validation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :ranking %><br>
    <%= f.select :ranking, Validation::RANKING_ITEMS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/ontrack_privat/app/views/validations/edit.html.erb
<h1>Editing Validation</h1>

<%= render 'form' %>

<%= link_to 'Show', project_validation_path(@project, @validation) %> |
<%= link_to 'Back', project_validations_path(@project) %>

Rails/Projekte/ontrack_privat/app/views/validations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Validations</h1>

<p>Ranking: <%= create_ranking(@project) %></p>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Username</th>
      <th>Ranking</th>
      <th>Bewertung</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @validations.each do |validation| %>
      <tr>
        <td><%= validation.comment %></td>
        <td><%= validation.username %></td>
        <td><%= show_stars(validation) %></td>
        <td><%= create_text(validation) %></td>
        <td><%= link_to 'Show', project_validation_path(@project, validation) %></td>
        <td><%= link_to 'Edit', edit_project_validation_path(@project, validation) %></td>
        <td><%= link_to 'Destroy', project_validation_path(@project, validation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Validation', new_project_validation_path(@project) %>

Rails/Projekte/ontrack_privat/app/views/validations/new.html.erb
<h1>New Validation</h1>

<%= render 'form' %>

<%= link_to 'Back', project_validations_path(@project) %>

Rails/Projekte/ontrack_privat/app/views/validations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @validation.comment %>
</p>

<p>
  <strong>Username:</strong>
  <%= @validation.username %>
</p>

<p>
  <strong>Ranking:</strong>
  <%= @validation.ranking %>
</p>


<%= link_to 'Edit', edit_project_validation_path(@project, @validation) %> |
<%= link_to 'Back', project_validations_path(@project) %>