Rails/Projekte/first_app/config/routes.rb
Rails.application.routes.draw do

  
  root "projects#index"

  resources :projects do
    resources :tasks
  end

end

Rails/Projekte/first_app/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy

	validates :title, length: { minimum: 5, message: "Der Titel muss mindestens 5 Zeichen enthalten!" }
	validate :start_date_cannot_be_in_the_past

	def start_date_cannot_be_in_the_past
	  errors.add(:start_date, "Das Datum muss in der Zukunft liegen!") if start_date.present? && start_date < Date.today
	end
end

Rails/Projekte/first_app/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

Rails/Projekte/first_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/Projekte/first_app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update, :destroy]

	def index
		@projects = Project.all
	end

	def show
		
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			flash[:notice] = "Eintrag erfolgreich erstellt :)"
			redirect_to projects_url
		else
			flash[:alert] = "Leider ist etwas schief gegangen :("
			render :new
		end
	end

	def edit
	end

	def update
		if @project.update(project_params)	
			flash[:notice] = "Update erfolgreich :)"	
			redirect_to projects_url
		else
			flash[:alert] = "Leider ist etwas schief gegangen :("
			render :edit
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_url
	end

	private
		def project_params
			params.require(:project).permit(:title, :description, :start_date)
		end

		def set_project
			@project = Project.find(params[:id])
		end
	
end

Rails/Projekte/first_app/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      flash[:notice] = "Erfolgreich gespeichert :)"
      redirect_to project_tasks_path(@project.id)
    else
      flash[:alert] = "Leider ist ein Fehler aufgetreten :("
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params) 
      flash[:notice] = "Update erfolgreich :)"  
      redirect_to project_task_path(@project.id, @task.id)
    else
      flash[:alert] = "Leider ist etwas schief gegangen :("
      render :edit
    end
    
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
    def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_tasks_url(@project.id), notice: "task von #{@task.title} erfolgreich gelöscht"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :start_date, :end_date, :project_id)
    end
end

Rails/Projekte/first_app/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/Projekte/first_app/app/helpers/projects_helper.rb
module ProjectsHelper
end

Rails/Projekte/first_app/app/helpers/tasks_helper.rb
module TasksHelper
end

Rails/Projekte/first_app/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<%= render "shared/errors", object: @project %>
	<div class="row">
		<div class="medium-3 columns">
			<%= f.label :title %>
		</div>
		<div class="medium-9 columns">
			<%= f.text_field :title %>
		</div>
	</div>
	<div class="row">	
		<div class="medium-3 columns">
			<%= f.label :description %>
		</div>
		<div class="medium-9 columns">
			<%= f.text_area :description %>
		</div>
	</div>
	<div class="row">	
		<div class="medium-3 columns">
			<%= f.label :start_date %>
		</div>
		<div class="medium-9 columns">
			<%= f.date_select :start_date %>
		</div>
	</div>
	<div class="row">
		<div class="medium-3 columns">
			&nbsp;
		</div>
		<div class="medium-9 columns">
			<%= f.submit "Speichern", class: "button" %>
			&nbsp;
			<%= link_to "Zurück", projects_path, class:"button" %>
		</div>
	</div>	
<% end %>

Rails/Projekte/first_app/app/views/projects/edit.html.erb
<h2>Editieren von <%=@project.title %></h2>

<%= render "form" %>

Rails/Projekte/first_app/app/views/projects/index.html.erb
<h1>
		<%if @projects.size == 1 %>
			<%="Projekt" %>
		<% else %>
			<%= "Projekte" %>
		<% end %>
</h1>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>Start Date</th>
			<th>Tasks</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @projects.each do | var | %>
			<tr>
				<td><%= var.title %></td>
				<td><%= var.description %></td>
				<td><%= var.start_date %></td>
				<td></td>
				<td><%= link_to "<i class='fi-eye'></i>".html_safe, project_path(var.id) %></td>
				<td><%= link_to "<i class='fi-pencil'></i>".html_safe, edit_project_path(var.id) %></td>
				<td><%= link_to "<i class='fi-trash'></i>".html_safe, project_path(var.id), method: :delete, data: {confirm: "Sind sie sicher?"} %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Neues Projekt anlegen", new_project_path %>

Rails/Projekte/first_app/app/views/projects/new.html.erb
<div class="row">
		<div class="medium-3 columns">
			<h3>Neues Projekt</h3>
		</div>
		<div class="medium-9 columns">
			&nbsp;
		</div>
	</div>	



<%= render "form" %>

Rails/Projekte/first_app/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p><%= @project.description %></p>

<p><%= @project.start_date %></p>


<p>
	<ul class="button-group">
		<li>
			<%= link_to "Alle Projekte anzeigen", projects_path, class: "button" %>
		</li>
	</ul>
</p>

<%= link_to "Tasks", project_tasks_path(@project.id), class: "button" %>

Rails/Projekte/first_app/app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<div class="panel">
		<h3>Opps! Der <%= object.class.name.titleize.downcase %> konnte nicht gespeichert werden.</h3>
		Korrigieren sie folgenden <%= pluralize(object.errors.count, "error") %>:
		<ul>
			<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>	
			<% end %>
		</ul>
	</div>
<% end %>

Rails/Projekte/first_app/app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/first_app/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>


<%= link_to 'Back', project_tasks_path(@project.id) %>

Rails/Projekte/first_app/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks for <%= @project.title %></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= link_to 'Show', project_task_path(@project.id, task.id) %></td>
        <td><%= link_to 'Edit', edit_project_task_path(@project.id, task.id) %></td>
        <td><%= link_to 'Destroy', project_task_path(@project.id, task.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path(@project.id) %>

Rails/Projekte/first_app/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path %>

Rails/Projekte/first_app/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<%= link_to 'Edit', edit_project_task_path(@project.id, @task) %> |
<%= link_to 'Back', project_tasks_path %>